alias: 'Turn on the TV when the living room lights are turned on'
trigger:
  platform: state
  entity_id: light.living_room
  to: 'on'
condition:
  - condition: state
    entity_id: media_player.tv
    state: 'off'
action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.tv