alias: 'Turn off the hallway lights when the front door is closed'
trigger:
  platform: state
  entity_id: binary_sensor.front_door
  to: 'off'
action:
  - service: light.turn_off
    target:
      entity_id: group.hallway_lights