alias: 'Turn on the living room lights when motion is detected'
trigger:
  platform: state
  entity_id: binary_sensor.living_room_motion
  to: 'on'
condition:
  condition: sun
  before: sunrise
  after: sunset
action:
  - service: light.turn_on
    target:
      entity_id: group.living_room_lights