alias: 'Turn off the living room lights when no motion is detected for 10 minutes'
trigger:
  platform: state
  entity_id: binary_sensor.living_room_motion
  to: 'off'
  for:
    minutes: 10
condition:
  - condition: state
    entity_id: light.living_room
    state: 'on'
action:
  - service: light.turn_off
    target:
      entity_id: light.living_room