alias: 'Turn on the living room lights when the TV is turned on'
trigger:
  platform: state
  entity_id: media_player.living_room_tv
  to: 'on'
condition:
  - condition: state
    entity_id: light.living_room
    state: 'off'
action:
  - service: light.turn_on
    target:
      entity_id: light.living_room