alias: 'Turn on the hallway lights when the front door is opened during nighttime'
trigger:
  platform: state
  entity_id: binary_sensor.front_door
  to: 'on'
condition:
  condition: sun
  after: sunset
  before: sunrise
action:
  - service: light.turn_on
    target:
      entity_id: group.hallway_lights