alias: 'Turn on the hallway light when the front door is opened during nighttime'
trigger:
  platform: state
  entity_id: binary_sensor.front_door
  to: 'on'
condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
action:
  - service: light.turn_on
    target:
      entity_id: light.hallway