alias: 'Turn on lights when person comes home'
trigger:
  platform: state
  entity_id: person.example_person
  to: 'home'
action:
  - service: light.turn_on
    target:
      entity_id: light.example_light