alias: 'Turn off the bedroom lights when no motion is detected for 10 minutes'
trigger:
  platform: state
  entity_id: binary_sensor.bedroom_motion
  to: 'off'
  for:
    minutes: 10
action:
  - service: light.turn_off
    target:
      entity_id: light.bedroom