alias: 'Turn off the bedroom lights when the alarm is disarmed'
trigger:
  platform: state
  entity_id: alarm_control_panel.home_alarm
  to: 'disarmed'
condition:
  - condition: state
    entity_id: light.bedroom
    state: 'on'
action:
  - service: light.turn_off
    target:
      entity_id: light.bedroom