alias: 'Turn on lights when person comes home and sun is under - Automation 3'
trigger:
  platform: state
  entity_id: person.example_person
  to: 'home'
condition:
  - condition: sun
    before: sunset
action:
  - service: light.turn_on
    target:
      entity_id: light.example_light