alias: 'Turn off the coffee machine after 30 minutes'
trigger:
  platform: state
  entity_id: switch.coffee_machine
  to: 'on'
  for:
    minutes: 30
action:
  - service: switch.turn_off
    target:
      entity_id: switch.coffee_machine