alias: 'Turn on the coffee machine when the first person wakes up'
trigger:
  platform: state
  entity_id: group.family
  from: 'asleep'
  to: 'home'
condition:
  condition: time
  after: '06:00:00'
  before: '10:00:00'
action:
  - service: switch.turn_on
    target:
      entity_id: switch.coffee_machine