alias: 'Notify when the washing machine has finished'
trigger:
  platform: state
  entity_id: sensor.washing_machine_power
  to: 'off'
condition:
  condition: state
  entity_id: input_boolean.washing_machine_notification
  state: 'on'
action:
  - service: notify.notify
    data:
      message: 'The washing machine has finished.'