alias: 'Turn on the bedroom lights when the alarm goes off'
trigger:
  platform: state
  entity_id: alarm_control_panel.house_alarm
  to: 'triggered'
condition:
  - condition: state
    entity_id: light.bedroom
    state: 'off'
action:
  - service: light.turn_on
    target:
      entity_id: light.bedroom