alias: 'Turn off the air conditioner when the window is opened'
trigger:
  platform: state
  entity_id: binary_sensor.window
  to: 'on'
condition:
  - condition: state
    entity_id: climate.air_conditioner
    state: 'cool'
action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.air_conditioner
    data:
      hvac_mode: 'off'