alias: 'Turn off the living room lights when the TV is turned off'
trigger:
  platform: state
  entity_id: media_player.living_room_tv
  to: 'off'
condition:
  - condition: state
    entity_id: light.living_room
    state: 'on'
action:
  - service: light.turn_off
    target:
      entity_id: light.living_room