alias: 'Turn on the porch light when the front door is unlocked'
trigger:
  platform: state
  entity_id: lock.front_door
  to: 'unlocked'
condition:
  condition: sun
  after: sunset
  before: sunrise
action:
  - service: light.turn_on
    target:
      entity_id: light.porch