alias: 'Lock the front door when everyone leaves the house'
trigger:
  platform: state
  entity_id: group.family
  to: 'not_home'
action:
  - service: lock.lock
    target:
      entity_id: lock.front_door