alias: 'Turn on living room lights when motion is detected'
trigger:
  platform: state
  entity_id: binary_sensor.living_room_motion
  to: 'on'
condition:
  condition: sun
  after: sunset
  before: sunrise
action:
  - service: light.turn_on
    target:
      entity_id: light.living_room