alias: 'Turn on the coffee machine when the alarm goes off in the morning'
trigger:
  platform: state
  entity_id: alarm_control_panel.home_alarm
  to: 'triggered'
condition:
  condition: time
  after: '06:00:00'
  before: '09:00:00'
action:
  - service: switch.turn_on
    target:
      entity_id: switch.coffee_machine